changed vue from version 2 to 3 including all dependencies like vuex …
Planning-Poker-Teams/planning-poker-web pull request #24
Opened 2021-12-09 09:05 UTC by JStiller

…and vue-router. I also removed vue-class-component and vue-property-decorator due to the lack of support. Instead i used the new composition api of vue3.

2021-12-13 09:24 UTC, jbarop requested changes

2021-12-13 09:24 UTC, jbarop commented on web/.eslintrc.js
> -    "@vue/prettier/@typescript-eslint"
Ich fand die meisten Regeln schon hilfreich und würde sie eigentlich gerne drin lassen. Wir sollten nur schauen, dass sie vielleicht beim Debuggen keinen Fehler erzeugen.

2021-12-13 09:24 UTC, jbarop commented on web/index.html
> +    <link rel="icon" href="/favicon.ico" />
Die BASE_URL kann wirklich raus?

2021-12-13 09:36 UTC, JStiller commented on web/package.json
> +    "email": "andreas@karroum.de"
Gefragt habe ich nicht. Aber genau diese E-Mail Adresse steht bei Github so öffentlich drin. Aber fragen wäre wohl dennoch sinnvoll!

2021-12-13 09:38 UTC, JStiller commented on web/.gitignore
> -.DS_Store
Die .gitignore ist im root-Verzeichnis.

2021-12-13 09:39 UTC, JStiller commented on web/package.json
> -    "eslint": "^6.7.2",
Können wir gerne drin lassen. Ist prinzipiell nur durch das preset von vite rausgefallen und habe es dann nicht wieder mit aufgenommen.

2021-12-13 09:41 UTC, JStiller commented on README.md
> +npm install
Ist prinzipiell nur durch das preset von vite geändert worden. Man kann aber weiterhin beides nutzten.

2021-12-13 09:42 UTC, JStiller commented on web/.eslintrc.js
> -    "@vue/prettier/@typescript-eslint"
Können wir gerne drin lassen. Ist prinzipiell nur durch das preset von vite rausgefallen und habe es dann nicht wieder mit aufgenommen.

2021-12-13 10:12 UTC, ejbyne requested changes

2021-12-13 10:12 UTC, ejbyne commented on web/src/components/OngoingEstimation.vue
> +  setup(props, context) {
Ich finde die setup Methoden viel zu lang, was das Zweck der Composition-API widerspricht. Hierzu wird as Prinzip in diesem Artikel gut erklärt: https://v3.vuejs.org/guide/composition-api-introduction.html#why-composition-api. Die Idee ist nicht, alles in eine Methode zu packen, sonder die verschiedenen Pakete von Logic in kleinere Functions auszulagern und zu zusammen zu komposen.

2021-12-13 10:12 UTC, ejbyne commented on README.md
> +npm install
Wir sollten uns hier eine Entscheidung treffen, weil entweder die yarn.lock oder die package-lock.json eingecheckt werden muss.

2021-12-13 10:12 UTC, ejbyne commented on web/index.html
> +    <link rel="icon" href="/favicon.ico" />
Ich würde auch denken, dass die BASE_URL von außen injected werden soll.

2021-12-13 10:12 UTC, ejbyne commented on web/package.json
> -    "eslint": "^6.7.2",
eslint würde ich auch gern behalten.

2021-12-13 10:53 UTC, JStiller commented on web/package.json
> +    "email": "andreas@karroum.de"
Habe gefragt und es ist in Ordnung.

2021-12-13 12:36 UTC, JStiller commented on web/package.json
> -    "eslint": "^6.7.2",
Ich habe es wieder hinzugefügt. Und nahezu alles gefixed, was bemängelt wurde. Unter anderem werden scheinbar aber auch keine Komponenten empfohlen, welche nur aus einem Wort bestehen. Also Room geht nicht. DefaultRoom schon. Habe diese Warnings bzw. Fehler erstmal ignoriert.

2021-12-13 12:39 UTC, JStiller commented on web/index.html
> +    <link rel="icon" href="/favicon.ico" />
Habe mir hierzu ein plugin gezogen, das "okay" ausgesehen hat um entsprechende Template-Variablen nutzten zu können.

2021-12-13 12:39 UTC, JStiller commented on web/index.html
> +    <title>Vite App</title>
Habe mir hierzu ein plugin gezogen, das "okay" ausgesehen hat um entsprechende Template-Variablen nutzten zu können.

2021-12-13 12:41 UTC, JStiller commented on README.md
> +```shell
Habe es jetzt erst einmal so gelöst, dass ich im Root eine weitere package.json erstellt habe, in der die Befehle, die Befehle aus dem Unterordner "referenzieren". Könnte man aus dem ganzen nicht ein Monorepo machen? Im Grunde haben wie hier ja zwei Repositories in einem, da sie inhaltlich zusammen gehören.

2021-12-13 12:48 UTC, JStiller commented on web/src/components/OngoingEstimation.vue
> +  setup(props, context) {
Ich habe es im Grunde so interpretiert, dass die setup Methode - salopp gesagt - im Grunde nur ein anderer "Wrapper" ist. Vorher standen die Inhalte in verschiedenen Objekten. Nur das der Vorteil in der setup Methode der ist, dass man Inhaltlich zusammengehörige Dinge auch zusammenschreiben kann. Aber unabhängig davon, würde ich hier sonst gerne vorschlagen ein gesonderte task daraus zu machen, da es in dem Task eigentlich darum ging es auf vue3 & Co zu migrieren. Würde diese Task dann auch gerne im Pair gemeinsam mit dir oder gerne auch gemeinsam im mop lösen.

2021-12-13 15:31 UTC, c-st requested changes
Danke für deine Mühe und den PR!  
Hilf mir aber bitte die Motivation des vue-Upgrades zu verstehen: was genau gewinnen wir damit?

Im Gegenteil: ich sehe derzeit die Vorteile (noch) nicht, sondern würde hinterfragen, ob es wirklich best-practice ist, alles in der `setup()`-Methode zusammenzubauen. Ich fand ehrlich gesagt die Trennung in Getter und Methoden für Seiteneffekte einen sinnvolleren Weg, die Logik der Komponente zu strukturieren.

Wenn durch die neue Vue-Version neue Features zur Verfügung stehen, die es ermöglichen die Komponenten besser zu schreiben (idiomatischer, besser testbar etc.) dann sollten wir die auch nutzen. Dafür ist ein +1 Projekt ja auch in erster Linie da :-).

2021-12-13 15:31 UTC, c-st commented on web/src/components/OngoingEstimation.vue
> +  setup(props, context) {
Ehrlich gesagt denke ich, es wäre eine gute Idee gewesen, diese Änderung erst nur exemplarisch an einer Komponente zu machen und sich Feedback mit einem draft PR zu holen. Auf der Basis hätte man dann diskutieren können. Jetzt hast du augenscheinlich schon recht viel Zeit in die Änderungen investiert. (Zusätzlich finde ich es echt schwer 45 Changes in einem PR sinnvoll durchzusehen).

Ist jetzt schon länger her, dass ich mit Vue gearbeitet habe und habe auch noch nicht mit der Composition-API gearbeitet. Aber ich sehe das ähnlich wie Ed: ich fand die Aufteilung in getter und Methoden für Seiteneffekte besser, als jetzt alles in `setup()` zu haben und sehe ehrlich gesagt den Mehrwert nicht. Wenn wir es auf die neue Vue-Version umbauen, sollten wir auch versuchen die neuen Features davon zu nutzen.

Wir hatten vorher schon wenig (keine?) Tests. Nun sehe ich hier zusätzlich das Problem, dass die neue Struktur mit so gut wie allem Code in `setup()` es noch schwerer macht, die Logik einer Komponente zu testen. Ich finde hier sollten wir ansetzen und sehen, wie wir die Testbarkeit erhöhen können.

2021-12-13 15:31 UTC, c-st commented on web/src/components/OngoingEstimation.vue
> +    const possibleEstimationValues = reactive([
muss das `reactive` sein? Die Werte an sich sollten sich doch nie ändern, oder?

2021-12-13 15:31 UTC, c-st commented on web/src/store/index.ts
> +export type Store = Omit<
Brauchen wir die Definition dieses `type`s bei uns oder kann man den auch direkt von Vue importieren?

2021-12-13 16:01 UTC, JStiller commented on web/package.json
> -    "test": "vue-cli-service test:unit --testMatch=\"**/+(*.)+(spec|test).+(ts|js)?(x)\"",
Jest ist drin, aber eben noch nicht konfiguriert. Muss da erstmal schauen, das bei der Build-In Lösung gemacht wurde. Dann kann ich es adaptieren.

2021-12-13 16:03 UTC, JStiller commented on README.md
> +```shell
Ich habe da keine Präferenzen. Mir ist beides recht. Und ja, Monorepo wäre definitiv separat. Soll ich es dann entsprechend abändern? Bitte 👍🏻 oder 👎🏻

2021-12-13 17:47 UTC, JStiller commented on README.md
> +npm install
Macht doch mal 👍🏻 für Yarn und 👎🏻 für npm. Ist wie gesagt nur durch das preset von vite zu npm gewechselt. Es wird beides funktionieren.

2021-12-13 17:53 UTC, JStiller commented on web/README.md
> +# Vue 3 + Vite
Ja, oder wir schreiben in diese Readme, spezifische Dinge bzgl. des Frontends. Und alle die allgemeinen Dinge, welche sowohl das Frontend als auch das Backend betreffen in die Readme im root.

2021-12-13 17:56 UTC, JStiller commented on web/package.json
> -  "lint-staged": {
Du beziehst dich auf gitHooks und lint-staged? Nein, wurde nicht bewusst enfernt. Wurde nur noch nicht überführt, so wie die anderen Dinge die schon aufgefallen waren.

2021-12-13 18:02 UTC, JStiller commented on web/src/components/OngoingEstimation.vue
> +    const possibleEstimationValues = reactive([
Habe es gerade mal getestet. Aktuell geht es auf jeden Fall auch ohne. Mit der Änderung von @jbarop wird das dann sehr wahrscheinlich wieder reactive werden. Aber das kann man dann ja wieder einbauen. Fürs erste reicht es auch ohne.

2021-12-13 18:14 UTC, JStiller commented on web/src/store/index.ts
> +export type Store = Omit<
Wenn es einen einfacheren Weg gibt und den State, Mutations, Actions und Getters einzubinden bin ich dafür!

2021-12-13 18:34 UTC, JStiller commented on package.json
> +  "private": true,
Weil das in der urspreünglichen package.json auch drin stand. Können das aber auch raus nehmen.

2021-12-13 18:52 UTC, JStiller commented on web/.browserslistrc
> -> 1%
Habe nun ein weiteres Plugin hinzugefügt um den Support hierzu erhalten. Die Config steht nun in der vite.config.js

2021-12-13 18:55 UTC, JStiller commented on web/package.json
> +    "@vitejs/plugin-vue": "1.9.3",
So lange wie Yarn/npm noch offen ist, dachte ich wäre es besser die pinnen. Wenn die Entscheidung gefallen ist, können wir das gerne wieder rausnehmen.

2021-12-13 19:08 UTC, JStiller commented on web/src/components/OngoingEstimation.vue
> +  setup(props, context) {
Kann dich/euch gut insgesamt verstehen. Ich habe auch jeden Tag mit vue zu tun. Für mich hat es sich jedoch schon gelohnt allein um mal wieder etwas in vue reinzukommen und zu lernen, was es alles zu beachten gibt wenn man von vue2 auf vue3 migriert. Also mache dir wegen der "vielen" Arbeit kein Kopf.

Mir war anfänglich ehrlich gesagt auch gar nicht klar, was das alles für ein Rattenschwanz mit sich zieht. Erst der fehlende Support für die Decorators, dann der "Zwang" zum update von vuex, vue-router und die neue Composition-API. Ich habe aber kein Weg gesehen eine lauffähige Version zu erhalten ohne all diese Änderungen durchzuführen.

Bzgl. des Tests hinsichtlich der `setup()` bin ich ganz bei euch. Das finde auch nicht geil. Vielleicht kann man sich die Teile ja mal gemeinsam ansehen und ein bessere Lösung finden?!

2021-12-13 19:30 UTC, c-st commented on web/index.html
> +    <title>Vite App</title>
Aber dann kann diese `index.html` gelöscht werden oder wozu braucht man sonst `<title>Vite App</title>`?

2021-12-13 19:30 UTC, c-st commented on README.md
> +npm install
Ich würde den Package-Manager nur wechseln, wenn es Sinn macht. Im Zweifelsfall würde ich nichts ändern und den benutzen, den wir auch im Backend im Einsatz haben. Außerdem sollten wir ja schon einen yarn-Lockfile eingecheckt haben.

Vite hat Support für diese hier: https://vitejs.dev/guide/#scaffolding-your-first-vite-project

2021-12-13 19:30 UTC, c-st commented on README.md
> +```shell
Vorschlag: nur eine in `web/package.json` und in der Readme entsprechend drauf verweisen.

2021-12-13 19:31 UTC, c-st commented on web/package.json
> +    "@vitejs/plugin-vue": "1.9.3",
Die verwendeten Versionen sind ja im Lockfile festgehalten. Ich würde die nur pinnen, wenn ganz bewusst eine bestimmte Version verwendet werden soll. Das sehe ich hier aber nicht.

2021-12-13 19:31 UTC, c-st commented on package.json
> +  "private": true,
Stimmt... das war drin dass wir das nicht versehentlich als Package publishen können. 

Siehe 
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#private
> If you set "private": true in your package.json, then npm will refuse to publish it.

2021-12-13 19:32 UTC, c-st commented on web/src/components/OngoingEstimation.vue
> +    const possibleEstimationValues = reactive([
Ja, denn das wird ja nicht in diesem PR gemacht 🙂

2021-12-13 19:35 UTC, c-st commented on web/README.md
> +# Vue 3 + Vite
In einem Monorepo könnten wir das so machen, da stimme ich dir zu. Aber das haben wir hier ja (noch) nicht 🙂. Soviel Code und Struktur dass man mehr als eine Readme bräuchte sehe ich hier ehrlich gesagt nicht. Würde mich auf eine im Root beschränken.

2021-12-13 19:36 UTC, c-st commented on web/README.md
> +# Vue 3 + Vite
Ich meinte eigentlich auch nur, die default Vite/Vue3 Readme rauszunehmen.

2021-12-13 19:37 UTC, c-st commented on web/package.json
> -    "test": "vue-cli-service test:unit --testMatch=\"**/+(*.)+(spec|test).+(ts|js)?(x)\"",
Zum Glück ist Jest recht pflegeleicht was Config angeht. Ein Beispiel ist z.B. hier: https://dev.to/vuesomedev/add-testing-to-vite-4b75

2021-12-13 19:39 UTC, c-st commented on web/package.json
> -  "lint-staged": {
Das soll ja den Linter ausführen, wenn man entsprechende Files gestaged hat. Der Linter ist doch noch/wieder drin?

2021-12-13 19:41 UTC, c-st commented on web/src/store/actions.spec.ts
> +      actions[ActionsType.REQUEST_START_ESTIMATION] as any
War zwar schon so, aber kommen wir irgendwie ohne das `as any` aus?

2021-12-13 19:55 UTC, c-st commented on web/src/components/OngoingEstimation.vue
> +  setup(props, context) {
Vielleicht wäre auch das eine Option für den Übergang: https://v3.vuejs.org/guide/migration/migration-build.html#overview

Dann ist man auf der v3, muss aber nicht sofort alle Komponenten ändern. Man kann sich dann in Ruhe Gedanken machen und eine schöne, testbare Lösung auf Basis der Composition-API bauen. 

Was Mobben/Pairen zu dem Thema betrifft: Ich nutze derzeit weder Vue.js noch Planning-Poker und habe momentan genug zu tun. Bin bei dem Thema also vorerst raus.

2021-12-13 20:38 UTC, JStiller commented on web/index.html
> +    <title>Vite App</title>
Die Index.html ist bereits outdated. Sprich habe es bereits soweit angepasst, dass es im Grunde wieder wie vorher funktioniert. Entsprechend kannst du einen Titel in der vite.config.js setzten, welcher dann in dem Template verwendet wird.

2021-12-13 20:48 UTC, JStiller commented on README.md
> +npm install
Macht sinn das selbe zu nutzten wie im backend. Habe es mal eben von npm auf yarn gewechselt. Und die gepinnten Versionen entfernt.

2021-12-14 09:06 UTC, jbarop commented on web/src/components/OngoingEstimation.vue
> +  setup(props, context) {
Wir haben uns entscheiden mit View3 und die Composition API zu nutzen. Stellen wie diese sind viel zu groß. Die werden wir stückchenweise verbessern.

2021-12-14 09:12 UTC, jbarop commented
> Danke für deine Mühe und den PR! Hilf mir aber bitte die Motivation des vue-Upgrades zu verstehen: was genau gewinnen wir damit?

Der eigentliche Problem war ein Update auf die aktuellste Tailwind version.

2021-12-15 09:27 UTC, jbarop approved these changes

2021-12-15 09:27 UTC, merged